### ISSUE TITLE
求增加在线播放功能

### ISSUE THREAD

**Issue by huluohu** [solidSpoon/DashPlayer#16]
大佬你好，请问有增加在线播放功能的计划吗。

比如支持SMB、WebDAV、jellyfin、Emby等协议就更棒了。

**Comment by solidSpoon** [comment]
您好. 目前没有这个计划, 这个 issue 我先关掉了

**Comment by huluohu** [comment]
> 您好. 目前没有这个计划, 这个 issue 我先关掉了

好的，谢谢哈
