### ISSUE TITLE
安装后无法在win上打开，报错

### ISSUE THREAD

**Issue by VSpade7** [solidSpoon/DashPlayer#19]
报错如图
![image](https://github.com/solidSpoon/DashPlayer/assets/46594083/82bd92f7-ca68-4fe1-9e84-7b399b9680c4)

**Comment by solidSpoon** [comment]
好的，我看看

**Comment by solidSpoon** [comment]
已经修复了，请您下载 V2.0.2 版本看看是不是解决了您的问题。抱歉。

**Comment by VSpade7** [comment]
可以了，感谢修复
