### ISSUE TITLE
启动报错 TypeError: Cannot open database

### ISSUE THREAD

**Issue by nmynxy** [solidSpoon/DashPlayer#20]
![屏幕截图 2024-01-26 211410](https://github.com/solidSpoon/DashPlayer/assets/51796740/bf22d840-f07e-4093-b200-9466bb940c38)
我花了几个小时试了网上几乎所有方法，最后重装系统依然报该错误。是不兼容e5平台？我另一台amd ryzen跑着没问题。

**Comment by solidSpoon** [comment]
好的，我看下

**Comment by solidSpoon** [comment]
已经修复了，请您下载 V2.0.2 版本看看是不是解决了您的问题。抱歉。

**Comment by solidSpoon** [comment]
该问题已被认定为重复，详细信息请查看主要的 #19
