### ISSUE TITLE
希望能增加快捷键视频变速功能

### ISSUE THREAD

**Issue by VSpade7** [solidSpoon/DashPlayer#23]
除了用于看英语视频，还拿来看其他带字幕的长学习视频。

这个播放器带字幕列表，可以很好地查看、预览当前时间点往后的字幕内容，因此也很适合观看学习长视频。

如果是长视频的话，倍速基本是必须的功能，希望能增加使用快捷键变速视频的功能，谢谢。

**Comment by solidSpoon** [comment]
可以的，我最近加下，之前有这个功能可能哪个版本忘记展示出来了。

**Comment by VSpade7** [comment]
> 可以的，我最近加下，之前有这个功能可能哪个版本忘记展示出来了。

除了快捷键加减速外，希望能够有几个自定义的速度档位能够直接使用快捷键跳转。辛苦~

**Comment by solidSpoon** [comment]
您好，久等了。

根据您的建议，截至 v3 版本，DashPlayer 新增了以下功能：

- 增加了调整播放速度的按钮以及对应的快捷键
- 当您浏览侧边栏字幕时将暂停侧边栏的自动滚动

V3 版本迁移到了新一代的框架。由于迁移后打包工具的变动，更新至此版本前建议您卸载老版本的 DashPlayer，并需要您重新填写腾讯云和有道智云的密钥。

祝您使用愉快！
