### ISSUE TITLE
最新的macos系统是使用不了吗

### ISSUE THREAD

**Issue by nammi97** [solidSpoon/DashPlayer#24]
<img width="632" alt="image" src="https://github.com/solidSpoon/DashPlayer/assets/88979778/abed9f3a-d750-459b-b76d-e6aeaa559279">
打开会有这样的错误

**Comment by solidSpoon** [comment]
您好 M 芯片的 macOS 请下载 `arm64.dmg`，你可能下载的是 Intel 芯片的安装包就会报这个错。

![image](https://github.com/solidSpoon/DashPlayer/assets/39454841/ca51bcf8-b653-466a-9b0d-a6711006cf5a)

由于这个应用目前没有签名，安装之后需要运行下面这个命令消除系统警告。

```bash
xattr -c /Applications/DashPlayer.app
```
