### ISSUE TITLE
能否增加一个选词组的功能

### ISSUE THREAD

**Issue by 214070779** [solidSpoon/DashPlayer#27]
功能推荐1:增加一个选词组
咱们的软件用起来很舒服，不过美中不足的是无法选多个单词，当美剧中说了一句话，大部分单词都认识，但是这些单词组成一句话就不太懂了，是否可以考虑增加一个这样的功能。类似下面的功能，这个是之前学习英语一个网站不错的功能。
<img width="919" alt="Screenshot 2024-04-04 at 18 36 39" src="https://github.com/solidSpoon/DashPlayer/assets/30347253/52d3d902-2a54-4a12-a74d-1e0a04be05e1">

功能推荐2:是否可通过这个选词组功能，推荐词组相关的美剧视频片段

了解到这个网站有英语片段，https://www.getyarn.io/ ，不知道是否可以用一下，里面可以通过搜索找到非常多的英语美剧片段，来加深我们的理解

**Comment by 214070779** [comment]
额外补充一个：能否增加一个清除播放记录的按钮，好多次想清除这个记录，找不到按钮。我指的是这一个哈。
<img width="562" alt="Screenshot 2024-04-04 at 23 15 00" src="https://github.com/solidSpoon/DashPlayer/assets/30347253/95894164-bebe-40d7-99cf-99ccf3fcf774">

**Comment by solidSpoon** [comment]
收到，感谢您推荐功能，我会考虑一下的。

**Comment by 214070779** [comment]
https://huilianyingyu.com/index 是这个网站，你可以登录我的账号来看，我的qq号是214070779.

**Comment by solidSpoon** [comment]
v4 版本增加了整句学习面板, 你可以在那里查询词组
