### ISSUE TITLE
如果自己有字幕 那如何导入到程序中呢

### ISSUE THREAD

**Issue by Alexhuihui** [solidSpoon/DashPlayer#32]
如果自己有字幕 那如何导入到程序中呢

**Comment by Yolo0001** [comment]
开发者你好，我选择一个字幕，但是跳出了这个错误Cannot read properties of undefined (reading 'trim')

**Comment by solidSpoon** [comment]
您好，评论框那可以上传附件，方便把字幕附件传过来看看吗？

**Comment by Yolo0001** [comment]
[英雄联盟：双城之战 第1季第01集.Arcane.[WEB.1080P]中英文字幕【官方译本】Arcane.S01E01.Welcome.to.the.Playground.1080p.NF.WEB-DL.DDP5.1.x264-TEPES.zip](https://github.com/user-attachments/files/15523994/1.01.Arcane.WEB.1080P.Arcane.S01E01.Welcome.to.the.Playground.1080p.NF.WEB-DL.DDP5.1.x264-TEPES.zip)

**Comment by solidSpoon** [comment]
> 开发者你好，我选择一个字幕，但是跳出了这个错误Cannot read properties of undefined (reading 'trim')

你看看这个版本解决了你的问题吗
https://github.com/solidSpoon/DashPlayer/releases/tag/v4.2.3

**Comment by Yolo0001** [comment]
Awesome!非常感谢作者。😘😘
