### ISSUE TITLE
切换下一句导致几率性卡死

### ISSUE THREAD

**Issue by fluidog** [solidSpoon/DashPlayer#36]
## Prerequisites
mac 平台安装最新版 dashplayer，播放包含 rst 文件的本地英文视频

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
切换下一句不会导致视频卡死

## Current Behavior
视频卡死

## Steps to Reproduce

1.点击有**方向键**或者 **d** 键切换下一句时，会**偶发**视频卡死的现象。切换其他视频后，可正常播放。

2.

3.

4.

## Your Environment

- Node version :
- electron-react-boilerplate version or branch :
- Operating System and version :
- Link to your project :

**Comment by solidSpoon** [comment]
你的意思是软件的其他地方没事，只是视频卡住了吗？

**Comment by fluidog** [comment]
> 你的意思是软件的其他地方还可以点击，只是视频卡住了吗？

是的，可以点击播放其他视频，刚才发现不仅下一句会触发，下方向键和左方向键都会触发， 只要多按左右键

**Comment by fluidog** [comment]
显示的是播放状态，但是视频是暂停的，按空格也没用
<img width="1440" alt="image" src="https://github.com/solidSpoon/DashPlayer/assets/31918437/7fe72dae-e793-4f56-8c08-aa585fd4f6dd">

**Comment by solidSpoon** [comment]
我这复现不出来啊，方便给我分享一集你那个视频吗

**Comment by fluidog** [comment]
https://github.com/solidSpoon/DashPlayer/assets/31918437/2fa89982-7448-41b1-94f1-a3786bb68e1b

这个是复现的视频，好像与具体视频没关系，随机视频卡死，原视频比较大，怎么分享给你

**Comment by fluidog** [comment]
> 我这复现不出来啊，方便给我分享一集你那个视频吗

复现视频拍给你了，原视频比较大，咋分享给你

**Comment by fluidog** [comment]
> > 我这复现不出来啊，方便给我分享一集你那个视频吗
> 
> 复现视频拍给你了，原视频比较大，咋分享给你
好像与具体视频没关系，是随机视频卡死

**Comment by fluidog** [comment]
原视频第三集复现过卡死问题，已上传附件

[Archive.zip](https://github.com/solidSpoon/DashPlayer/files/15369378/Archive.zip)

**Comment by fluidog** [comment]
> 我这复现不出来啊，方便给我分享一集你那个视频吗

已上传

**Comment by solidSpoon** [comment]
您好，用你的视频确实复现出来了。

我把那个视频拖到 Chrome 浏览器里按左右键跳转一会也会卡死，应该是视频有点问题，建议你重新编码一下：

```bash
ffmpeg -i '003_Wizard and Cat 3_Into the Dark Forest.mp4' -c:v libx264 -preset fast -crf 22 -c:a copy '003_Wizard and Cat 3_Into the Dark Forest-n.mp4'
```

**Comment by fluidog** [comment]
> 您好，用你的视频确实复现出来了。
> 
> 我把那个视频拖到 Chrome 浏览器里按左右键跳转一会也会卡死，应该是视频有点问题，建议你重新编码一下：
> 
> ```shell
> ffmpeg -i '003_Wizard and Cat 3_Into the Dark Forest.mp4' -c:v libx264 -preset fast -crf 22 -c:a copy '003_Wizard and Cat 3_Into the Dark Forest-n.mp4'
> ```

哦哦，我之后试一下，辛苦你了哈。顺便夸一句你开发的软件对英语学习者的帮助真的很大

**Comment by solidSpoon** [comment]
谢谢您夸奖 🙏

**Comment by fluidog** [comment]
> > 您好，用你的视频确实复现出来了。
> > 我把那个视频拖到 Chrome 浏览器里按左右键跳转一会也会卡死，应该是视频有点问题，建议你重新编码一下：
> > ```shell
> > ffmpeg -i '003_Wizard and Cat 3_Into the Dark Forest.mp4' -c:v libx264 -preset fast -crf 22 -c:a copy '003_Wizard and Cat 3_Into the Dark Forest-n.mp4'
> > ```
> 
> 哦哦，我之后试一下，辛苦你了哈。顺便夸一句你开发的软件对英语学习者的帮助真的很大

试了一下，确实是视频的问题，多谢大佬
