### ISSUE TITLE
可不可以支持Xbox手柄呀？感谢！

### ISSUE THREAD

**Issue by nscmiaoxin** [solidSpoon/DashPlayer#40]
可不可以支持Xbox手柄呀？感谢！

**Comment by solidSpoon** [comment]
我手上还没有 Xbox 手柄 😂, 手柄播放那个功能原理是我发现有些小尺寸的手柄可以伪装成键盘连接电脑. 跟键盘快捷键一样的. 所以只要有这个功能的手柄应该都可以用.

除了我推荐那款我还刷到过好多款, 各个样式价位的都有, 不过我没买过其他牌子的
