### ISSUE TITLE
可以添加单词复制或者整句复制的功能吗？

### ISSUE THREAD

**Issue by hxlcw** [solidSpoon/DashPlayer#48]
有些时候我想复制一个单词 或者 复制一整个句子到GPT上分析语法

**Comment by solidSpoon** [comment]
目前你可以按 `?` 打开整句学习面板，在那里复制，即使不配置 openai 也可以打开面板的。

**Comment by hxlcw** [comment]
刚试了，可以复制。 稍稍有点麻烦，但也够用了。感谢 🙏

**Comment by solidSpoon** [comment]
主要是播放器界面开放复制的话很容易点单词发音的时候选择上文本，好烦 😂

**Comment by hxlcw** [comment]
> 主要是播放器界面开放复制的话很容易点单词发音的时候选择上文本，好烦 😂

大佬，我提交了一个 Pull request ，你可以看看怎么样？

**Comment by solidSpoon** [comment]
好的，我看看

**Comment by solidSpoon** [comment]
看到了, 待会我处理一下

**Comment by solidSpoon** [comment]
您好，我合并了你的请求，但是你却没有出现在贡献者列表，是没配置好邮箱吗？

https://docs.github.com/zh/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors

**Comment by hxlcw** [comment]
是我公司的 git客户端没有配置邮箱 😄 ，明天去配置一下
