### ISSUE TITLE
升级到最新版本后，从PLAY选项里面打开文件目录，里面的文件看不到了？（实际目录里面是有文件的）是什么原因？

### ISSUE THREAD

**Issue by raymanliming** [solidSpoon/DashPlayer#51]
## Prerequisites

- [ ] Using npm
- [ ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Node version :
- electron-react-boilerplate version or branch :
- Operating System and version :
- Link to your project :

**Comment by solidSpoon** [comment]
![image](https://github.com/solidSpoon/DashPlayer/assets/39454841/6cd0d35a-7327-4615-b723-dfd7409ff1ff)
看起来是限制文件后缀那多了一个点, 稍后我修复一下

**Comment by solidSpoon** [comment]
在 v4.2.2 中修复了
