### ISSUE TITLE
windows11下没有声音

### ISSUE THREAD

**Issue by nitianchi** [solidSpoon/DashPlayer#54]
## Summary

windows11下，音量合成器中没有该应用，所以没有声音，换了别的版本也没用

**Comment by solidSpoon** [comment]
您好, 是 MKV 格式的视频吗? 有的 MKV 音频编码不支持, 可以转成 MP4 那个功能转换试一下.

![image](https://github.com/solidSpoon/DashPlayer/assets/39454841/27430d29-3bb5-44b5-add6-7c571b4272f4)

**Comment by nitianchi** [comment]
感谢

> 您好, 是 MKV 格式的视频吗? 有的 MKV 音频编码不支持, 可以转成 MP4 那个功能转换试一下.
> 
> ![image](https://private-user-images.githubusercontent.com/39454841/335101629-27430d29-3bb5-44b5-add6-7c571b4272f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTgyMTcsIm5iZiI6MTcxNzA1NzkxNywicGF0aCI6Ii8zOTQ1NDg0MS8zMzUxMDE2MjktMjc0MzBkMjktM2JiNS00NGI1LWFkZDYtN2M1NzFiNDI3MmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA4MzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNWY0MjRkMzRmZjMzZGMxODI3MDc4MGU1MzA2ZDYzMTFkZDAwYWJjMmMyYmExY2EyNzc2ZjJiNmEwMTlmNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8r-SvXUBw5naRaaQasBbsTLuWmd7wpSsP_CIOaiNLqI)

感谢
