### ISSUE TITLE
字幕调整功能n，m调整句子结尾无效，只有z，x快捷键调整句子开头有效

### ISSUE THREAD

**Issue by danzh2000** [solidSpoon/DashPlayer#66]
作者您好！！软件非常好用，感谢您无偿的分享！！！

但有一个小小的bug～～bug如标题，我测试了不同设备，在调整字幕时间戳的功能中，发现只有调整句子开头开始时间有效（快捷键z,x），调整句子结尾时间的操作无效（快捷键n，m）。然后字幕开头的移动遇到边界条件也会出一些问题。我录制了一个视频，希望作者能够看到！链接我放在

【超级会员V5】通过百度网盘分享的文件：2024-07-....mov
链接：https://pan.baidu.com/s/1-GRosRY25XXsBQQZctW4wA?pwd=F11m 
提取码：F11m 
复制这段内容打开「百度网盘APP 即可获取」

我们非英语母语的人，需要克服的一个难关就是母语者快速的连读，这些连读很难听懂，需要大量练习，所以需要配合dashplay反复精听，但openai生成的字幕总是不那么准，句子没有被准确的分割，需要手动调整。所以希望作者能够关注到这个问题，看看是我的操作不当还是程序需要改善～～～谢谢！！！

**Comment by solidSpoon** [comment]
我也感觉有时候调整结尾时间不太好用，稍后我看下你发的视频。

**Comment by solidSpoon** [comment]
因为调整时间需要考虑会不会和其他行的时间冲突，比较棘手。最近我想到了解决办法，目前看起来效果不错，不过要等到下个大版本更新时一块发布。
