### ISSUE TITLE
mac apple m1 芯片的机器打不开

### ISSUE THREAD

**Issue by jeffrey-bin** [solidSpoon/DashPlayer#71]

**Comment by solidSpoon** [comment]
您好，具体报什么错，下载的是 arm64.dmg 吗？

DashPlayer-4.2.3-arm64.dmg

然后这个应用没有进行签名，m1 电脑安装后打开前要运行一下下面的命令，不然会报错文件损坏

```bash
xattr -c /Applications/DashPlayer.app
```

**Comment by jeffrey-bin** [comment]
<img width="1561" alt="image" src="https://github.com/user-attachments/assets/4af6d1de-3606-4483-8fa3-35d225c0b51e">
提示 不可以迭代 在哪里可以看到日志吗？

**Comment by solidSpoon** [comment]
应该没记下来，试试这个命令

```bash
/Applications/DashPlayer.app/Contents/MacOS/dash-player
```

**Comment by jeffrey-bin** [comment]
这个人工智能生成字幕的功能，我看文档应该是不需要我提供字幕文件，只需要提供一个 mp4 就行对吗？

**Comment by solidSpoon** [comment]
是的，调的 Whisper 接口
