### ISSUE TITLE
配置好API后没反应

### ISSUE THREAD

**Issue by xinf19** [solidSpoon/DashPlayer#80]
![屏幕截图 2024-10-10 121206](https://github.com/user-attachments/assets/7396c4c5-c6df-42f2-bdd9-65eaf731bd67)
![屏幕截图 2024-10-10 121312](https://github.com/user-attachments/assets/2a03d6aa-641c-4ead-9b8f-efe41b71a0c6)

**Comment by solidSpoon** [comment]
在open file 那选个srt文件就可以了。也可以同时选择视频和字幕然后点确定。

**Comment by xinf19** [comment]
> 在open file 那选个srt文件就可以了。也可以同时选择视频和字幕然后点确定。

感谢你，按照你的方法，我解决了问题
