### ISSUE TITLE
我要学日语，想请问怎么设置让openai transcribe的时候生成日语字幕？现在默认是生成翻译后的英文字幕

### ISSUE THREAD

**Issue by onyukito** [solidSpoon/DashPlayer#84]

**Comment by solidSpoon** [comment]
DashPlayer目前只对英语做了优化，支持多语言之前想实现来着，遇到了一些难点就暂时搁置了。所以看日语视频可能效果不太好。

看日语视频的话，可以试试这个网站，https://www.languagereactor.com 里面可以播放本地视频，我之前就用的这个。

生成字幕可以找一些专门做字幕生成的软件，比如我之前用过 MacWhisper https://goodsnooze.gumroad.com/l/macwhisper
和 Memo https://memo.ac/ 应该有很多这种软件你可以搜搜

**Comment by onyukito** [comment]
多谢！
