### ISSUE TITLE
字幕翻译不起作用， 字幕是ai生成的， 配了腾讯云api ，但是不会翻译， 有道的查词起作用 

### ISSUE THREAD

**Issue by ZongrongLi** [solidSpoon/DashPlayer#90]
## Prerequisites

- [ ] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Node version :
- electron-react-boilerplate version or branch :
- Operating System and version :
- Link to your project :

**Comment by jklrty** [comment]
同样的问题，请问如何解决？
