### ISSUE TITLE
ai 整句学习无法使用

### ISSUE THREAD

**Issue by Andrewxu1024** [solidSpoon/DashPlayer#99]
<img width="1916" alt="image" src="https://github.com/user-attachments/assets/7b3a22b8-f34b-40d2-a565-78fc5c9a3e9a" />

**Comment by solidSpoon** [comment]
![image](https://github.com/user-attachments/assets/2177e966-0d40-480c-a59a-40476d5e10c5)
参照我这个试下，然后可以把下面的 Streaming Response 关掉试下

**Comment by Andrewxu1024** [comment]
可以了可以了，阿里嘎多
